# Generated by Django 4.0.2 on 2022-02-26 14:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created_at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified_at')),
                ('first_name', models.CharField(max_length=100, verbose_name='names')),
                ('last_name', models.CharField(max_length=100, verbose_name='names')),
                ('email', models.EmailField(error_messages={'unique': 'A client with that email already exists.'}, max_length=254, unique=True, verbose_name='email address')),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +999999999. Up to 15 digits allowed.', regex='\\+?1?\\d{9,15}$')])),
                ('address', models.TextField(blank=True, max_length=250, null=True)),
                ('city', models.CharField(max_length=30, null=True, verbose_name='city')),
                ('state', models.CharField(max_length=30, null=True, verbose_name='state')),
                ('zip_code', models.CharField(max_length=30, null=True, verbose_name='zip')),
                ('country', models.CharField(max_length=30, null=True, verbose_name='country')),
                ('county', models.CharField(blank=True, max_length=30, null=True, verbose_name='county')),
                ('route', models.CharField(blank=True, max_length=30, null=True, verbose_name='route')),
                ('street_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='street number')),
                ('neighborhood', models.CharField(blank=True, max_length=30, null=True, verbose_name='neighborhood')),
                ('latitude', models.DecimalField(blank=True, decimal_places=20, max_digits=30, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=20, max_digits=30, null=True, verbose_name='longitude')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
