# Generated by Django 4.0.2 on 2022-03-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='birthday',
            field=models.DateTimeField(help_text='Day the equipment was purchased.', null=True, verbose_name='birthday'),
        ),
    ]
