# Generated by Django 4.0.2 on 2022-03-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_clients_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='username',
            field=models.EmailField(error_messages={'unique': 'A client with that username already exists.'}, max_length=30, null=True, unique=True, verbose_name='username'),
        ),
    ]
