version: "3.3"

services:
  app:
    container_name: django_unicloud
    build: 
        context: .
        dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8002:8000
    depends_on:
      - postgres

  postgres:
    container_name: postgres_unicloud
    image: postgres:14.1
    command: postgres -c stats_temp_directory=/tmp
    volumes:
      - ./docker/psql:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DBNAME}
      POSTGRES_USER: ${DBUSER}
      POSTGRES_PASSWORD: ${DBPASSWORD}
      POSTGRES_DBPORT: ${DBPORT}




  