version: "3.3"

services:
  app:
    container_name: django_backend
    build:
        context: .
        dockerfile: Dockerfile
    command:
      - /bin/sh
      - '-c'
      - '/code/entrypoint.sh'
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - postgres
  postgres:
    container_name: postgres_backend
    image: postgres:14.1
    command: postgres -c stats_temp_directory=/tmp
    volumes:
      - .docker/psql:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DBNAME}
      POSTGRES_USER: ${DBUSER}
      POSTGRES_PASSWORD: ${DBPASSWORD}
      POSTGRES_DBPORT: ${DBPORT}
    ports:
      - 5432:5432
