# Generated by Django 4.0.2 on 2022-08-16 14:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created_at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified_at')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='name')),
                ('address', models.TextField(max_length=250)),
                ('company', models.CharField(max_length=30, verbose_name='company name')),
                ('company_abbrevation', models.CharField(max_length=5, verbose_name='company abbreviation')),
                ('phone_contact', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +999999999. Up to 15 digits allowed.', regex='\\+?1?\\d{9,15}$')])),
                ('abbreviation', models.CharField(max_length=5, verbose_name='abbreviation')),
                ('is_active', models.BooleanField(default=True)),
                ('email', models.EmailField(error_messages={'unique': 'A Company with that email already exists.'}, max_length=30, unique=True, verbose_name='email address')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
