on:
  push:
    branches: [main]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_REGISTRY: dockerhub.uni.cloud
jobs:
  build-and-push:
    name: build and push image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKER_REGISTRY }}/dev-tools-image:${{ github.sha }}
            ${{ env.DOCKER_REGISTRY }}/dev-tools-image:latest

  deploy-to-cluster:
    name: deploy to cluster
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: deploy to cluster
      uses: steebchen/kubectl@v2.0.0
      with: # defaults to latest kubectl binary version
        config: ${{ secrets.KUBERNETES_SECRET }}
        command: set image deployment/django-devtools django-devtools=dockerhub.uni.cloud/dev-tools-image:latest
    - name: verify deployment
      uses: steebchen/kubectl@v2.0.0
      with:
        config: ${{ secrets.KUBERNETES_SECRET }}
        version: v1.27.4
        binaries-url: "https://dl.k8s.io/release/v1.21.0/bin/linux/amd64/kubectl" 
        command: rollout status deployment/django-devtools
